USE test;

DROP TABLE PART_DETAIL;
DROP TABLE PART;
DROP TABLE VENDOR;
DROP TABLE VENDOR_PART;
DROP TABLE LINEITEM;
DROP TABLE `ORDER`;

CREATE TABLE IF NOT EXISTS `ORDER` (
	ID BIGINT,
    DISCOUNT INT,
    LAST_UPDATE DATETIME,
    SHIPMENT_INFO VARCHAR(255),
    STATUS CHAR(1)
);

CREATE TABLE IF NOT EXISTS LINEITEM (
	ID BIGINT,
    ORDER_ID BIGINT,
    QUANTITY INT,
    VENDOR_PART_ID BIGINT
);

CREATE TABLE IF NOT EXISTS VENDOR_PART (
	ID BIGINT,
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(52,0),
    VENDOR_ID BIGINT,
    PART_NUMBER VARCHAR(255),
    PART_REVISION INT
);

CREATE TABLE IF NOT EXISTS VENDOR (
	ID BIGINT,
    ADDRESS VARCHAR(255),
    CONTACT VARCHAR(255),
    NAME VARCHAR(255),
    PHONE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PART (
	NUMBER VARCHAR(255),
    REVISION INT,
    DESCRIPTION VARCHAR(255),
    REVISION_DATE DATE,
    BOM_NUMBER VARCHAR(255),
    BOM_REVISION INT
);

CREATE TABLE IF NOT EXISTS PART_DETAIL (
	PART_NUMBER VARCHAR(255),
    PART_REVISION INT,
    DRAWING BLOB,
    SPECIFICATION BLOB
);